name: Python Pull Request Workflow
on: [pull_request]
jobs:

  qa:
    
    name: Quality check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clear Python cache
        run: |
          rm -rf ~/.cache/pip
          rm -rf ~/.cache/actions
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test
        run: |
          python manage.py test

      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
